<nav class="navbar navbar-default navbar-inverse" role="navigation">
	<div class="navigation-list container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="/" class="navbar-brand">
				<strong>JLDMP</strong>&nbsp;
				Admin
			</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="<?php echo $page == 'ministry' ? 'active' : ''; ?>"><a href="/ministry">Ministry</a></li>
				<li class="<?php echo $page == 'event' ? 'active' : ''; ?>"><a href="/events">Events</a></li>
				<li class="<?php echo $page == 'schedule' ? 'active' : ''; ?>"><a href="/schedule">Schedules</a></li>
				<li><a href="/qa">Q & A</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome Michael <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="#"><i class="fa fa-gear"></i>&nbsp; Settings</a></li>
						<li><a href="/logout"><i class="fa fa-sign-out"></i>&nbsp; Logout</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>
