<!DOCTYPE html>
<html class="<?php print $class; ?>">
	
<head>
	<title><?php print $title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<?php if(isset($meta) && is_array($meta)): ?>
    <?php foreach($meta as $name => $content): ?>
    <meta name="<?php print $name; ?>" content="<?php print $content; ?>" />
    <?php endforeach; ?>
    <?php endif; ?>
		
	<!-- open sans font	 -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/bootstrap.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/font-awesome.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/control.css" />

    <link rel="stylesheet" type="text/css" href="/assets/styles/control/<?php echo $class; ?>.css"></script>
	
	<script type="text/javascript" src="/assets/scripts/jquery.js"></script>
	<script type="text/javascript" src="/assets/scripts/jquery.form.js"></script>
	<script type="text/javascript" src="/assets/scripts/bootstrap.js"></script>
</head>

<body>
	<div class="page">
		<div class="head"><?php echo $head; ?></div>
		<div class="body"><?php echo $body; ?></div>
		<div class="foot"><?php echo $foot; ?></div>
		
		<script type="text/javascript" src="/assets/scripts/control/login.js"></script>
		<script type="text/javascript" src="/assets/scripts/control/<?php echo $class; ?>.js"></script>
    </div>
</body>
</html>
