<div class="events-container">
	<section class="event-header page-header clearfix">
		<h2 class="pull-left">Events <small>Settings</small></h2>
		<a href="/event/add" class="btn btn-success add-event pull-right">
			<i class="fa fa-plus-circle"></i>&nbsp; Add Event
		</a>
	</section>
	<div class="row">
		<section class="col-md-3">
			<div class="list-group">
				<a href="/events" class="list-group-item
				<?php echo $var == null ? 'active' : ''; ?>">
					<i class="fa fa-th-list"></i>&nbsp; All
				</a>
				<a href="/events/active" class="list-group-item
				<?php echo $var == 'active' ? 'active' : ''; ?>">
					<i class="glyphicon glyphicon-ok"></i>&nbsp; Active
				</a>
				<a href="/events/not-active" class="list-group-item
				<?php echo $var == 'not-active' ? 'active' : ''; ?>">
					<i class="glyphicon glyphicon-remove"></i>&nbsp; Not Active
				</a>
			</div>
		</section>

		<section class="events-main col-md-9">
			<div class="event-search row">
				<form action="" method="get" class="search-event-form col-md-4">
					<div class="input-group">
						<input type="text" name="q" class="form-control" placeholder="Search Event" 
						value="<?php echo isset($_GET['q']) ? $_GET['q'] : ''; ?>" <?php echo isset($_GET['q']) ? 'autofocus' : ''; ?>>

						<span class="input-group-btn">
							<input type="submit" class="btn btn-warning" value="Search">
						</span>
					</div>
				</form>
				<div class="col-md-8">
					<ul class="pagination pagination-sm pull-right">
						<?php $range = $pg+5; $start = $range - 10; ?>
						<?php $start = $start < 1 ? 1 : $start; ?>
						<?php for($i = $start; $i <= $pages; $i++): ?>
							<li<?php echo $i == $pg ? ' class="active"' : NULL; ?>>
								<a href="?page=<?php echo $i; ?><?php echo isset($_GET['q']) && $_GET['q'] ? '&q='.$_GET['q'] : ''; ?>">
									<?php echo $i; ?>
								</a>
							</li>
							<?php if($range == $i) break; ?>
						<?php endfor; ?>
					</ul>
				</div>
			</div>
			<div class="event-list clearfix">
				<table class="table table-striped table-bordered">
					<thead>
						<th>ID</th>
						<th>Image</th>
						<th>Title</th>
						<th>Type</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Event Updated</th>
					</thead>
					<tbody>
						<?php if (!empty($events)): ?>
							<?php foreach ($events as $event): ?>
								<tr>
									<td><?php echo $event['event_id']; ?></td>
									<td>
										<div class="thumbnail">
											<?php if (!empty($event['event_image'])): ?>
												<img src="/uploads/event/<?php echo $event['event_image']['file_name']; ?>" width="80">
											<?php else: ?>
												<img src="/assets/images/placeholder.png" width="80">
											<?php endif ?>
										</div>
									</td>
									<td>
										<?php 
											switch ($event['event_active']) {
												case 0:	$active = 'not-active'; $badge = 'danger'; break;
												case 1:	$active = 'active'; $badge = 'success'; break;
											}
										 ?>
										<strong><?php echo $event['event_title']; ?></strong><br><br>
										
										<div class="pull-right">
											<span class="badge alert-<?php echo $badge; ?>"><strong><?php echo $active; ?></strong></span> |
											<a href="/event/view/<?php echo $event['event_id']; ?>" class="event-action-btn">
												<i class="fa fa-share"></i>&nbsp; View
											</a> |
											<a href="/event/edit/<?php echo $event['event_id']; ?>" class="event-action-btn">
												<i class="fa fa-pencil-square"></i>&nbsp; Edit
											</a> |
											<a href="/events?action=remove_event&id=<?php echo $event['event_id']; ?>"
											class="event-action-btn remove-event">
												<i class="fa fa-times-circle"></i>&nbsp; Remove
											</a>
										</div>
									</td>
									<td><?php echo $event['event_type'] == 'ministry' ? $event['event_type'] : 'general'; ?></td>
									<td><?php echo date('F j, Y', $event['event_start']); ?></td>
									<td><?php echo date('F j, Y', $event['event_end']); ?></td>
									<td><?php echo date('Y-m-d', $event['event_updated']); ?></td>
								</tr>
							<?php endforeach ?>
						<?php else: ?>
							<tr><td colspan="7">No events returned.</td></tr>
						<?php endif ?>
					</tbody>
				</table>
			</div>
		</section>
	</div>
</div>