<div class="container login">
	<h1><i class="fa fa-gears fa-2x"></i><strong>&nbsp; JLDMP Admin</strong></h1><br>
	<div class="login-form panel panel-success">
		<div class="panel-heading">
			<h4><i class="fa fa-unlock-alt"></i>&nbsp; Control Login</h4>
		</div>
		<div class="panel-body">
			<?php include(dirname(__FILE__).'/_msg.phtml'); ?>
			<form action="" method="post" role="form">
				<div class="controls">
					<div class="form-group input-group">
						<span class="input-group-addon"><i class="fa fa-user"></i></span>
						<input type="text" class="form-control" name="username" placeholder="Username" autofocus>
					</div>
					<div class="form-group input-group">
						<span class="input-group-addon"><i class="fa fa-key"></i></span>
						<input type="password" class="form-control" name="password" placeholder="Password">
					</div>
					<input type="submit" name="login" class="btn btn-success" value="Submit">
				</div>
			</form>
		</div>
	</div>
</div>