<link rel="stylesheet" href="/assets/styles/cropper.css">
<link rel="stylesheet" href="/assets/cropper-master/examples/crop-avatar/css/crop-avatar.css">

<div class="ministry-member-add-container">
	<ol class="breadcrumb">
		<li><a href="/">Home</a></li>
		<li><a href="/ministries">Ministry List</a></li>
		<li><a href="/ministry/<?php echo $ministry_id; ?>/members">Members</a></li>
		<li class="active">Add</li>
	</ol>

	<section class="page-header ministry-header clearfix">
		<h2 class="pull-left">Add Member</h2>
		<a href="/ministry/<?php echo $ministry_id; ?>/members" class="btn btn-success pull-right"><i class="fa fa-th-list"></i>&nbsp; Back to Member List</a>
	</section>
	
	<section class="ministry-member-main container">
		<?php include(dirname(__FILE__).'/../_menu.phtml'); ?>

		<?php foreach ($errors as $error): ?>
			<div class="alert alert-danger"><?php echo $error; ?></div><br>
		<?php endforeach ?>

		<?php include(dirname(__FILE__).'/../../_msg.phtml'); ?>

		<div class="row">
			<div class="col-md-3">
				<div class="panel panel-default">
					<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; News Images</div>
					<div class="panel-body" id="crop-avatar">
						<div class="news-image avatar-view" title="Upload News Image">
							<?php if (!empty($_SESSION['member_tmpimage'])): ?>
								<img src="/uploads/member/<?php echo $_SESSION['member_tmpimage']['file_name']; ?>">
							<?php else: ?>
								<img src="/assets/images/placeholder.png">
							<?php endif ?>

							<span class="btn btn-success btn-sm">
								<i class="fa fa-image"></i>&nbsp; Upload News Photo
							</span>
						</div>

						<div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
							<div class="modal-dialog modal-lg">
								<div class="modal-content">
									<form class="avatar-form" method="post" action="" enctype="multipart/form-data">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal">&times;</button>
											<h4 class="modal-title" id="avatar-modal-label">Change Avatar</h4>
										</div>
										<div class="modal-body">
											<div class="avatar-body">
												<!-- Upload image and data -->
												<div class="avatar-upload">
													<input class="avatar-src" name="avatar_src" type="hidden">
													<input class="avatar-data" name="avatar_data" type="hidden">
													<label for="avatarInput">Local upload</label>
													<input class="avatar-input" id="avatarInput" name="file" type="file">
												</div>

												<!-- Crop and preview -->
												<div class="row">
													<div class="col-md-9">
														<div class="avatar-wrapper"></div>
													</div>
													<div class="col-md-3">
														<div class="avatar-preview preview-lg"></div>
														<div class="avatar-preview preview-md"></div>
														<div class="avatar-preview preview-sm"></div>
													</div>
												</div>
											</div>
										</div>
										<div class="modal-footer">
											<button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
											<button class="btn btn-primary avatar-save" type="submit">Save</button>
										</div>
									</form>
								</div>
							</div>
						</div><!-- /.modal -->
					</div>
				</div>
			</div>
			<div class="col-md-9">
				<div class="panel panel-default">
					<div class="panel-heading">
						<i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Create Member
					</div>
					<div class="panel-body">
						<form action="" method="post" class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="member_fullname">Full Name</label>
									<input type="text" name="fullname" id="ministry_fullname" class="form-control" placeholder="Member Full Name"
									value="<?php echo isset($post['fullname']) ? $post['fullname'] : ''; ?>">
								</div>
								<div class="form-group">
									<label for="member_email">Email</label>
									<input type="text" name="email" id="ministry_email" class="form-control" placeholder="Member Email" 
									value="<?php echo isset($post['email']) ? $post['email'] : ''; ?>">
								</div>
								<div class="form-group">
									<label for="member_phone">Phone</label>
									<input type="text" name="phone" id="ministry_phone" class="form-control" placeholder="Member Phone" 
									value="<?php echo isset($post['phone']) ? $post['phone'] : ''; ?>">
								</div>
								<div class="form-group">
									<label for="member_fullname">Address</label>
									<textarea name="address" class="form-control" cols="30" rows="5" placeholder="Member Address"><?php echo isset($post['address']) ? $post['address'] : ''; ?></textarea>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="member_age">Age</label>
									<input type="text" name="age" id="ministry_age" class="form-control" placeholder="Member Age" 
									value="<?php echo isset($post['age']) ? $post['age'] : ''; ?>">
								</div>
								<div class="form-group">
									<label for="member_age">Type</label>
									<select name="type" class="form-control">
										<option value="coordinator"
										<?php echo isset($post['type']) && $post['type'] == 'coordinator' ? 'selected="selected"' : ''; ?>>Coordinator</option>

										<option value="president"
										<?php echo isset($post['type']) && $post['type'] == 'president' ? 'selected="selected"' : ''; ?>>President</option>
										
										<option value="vice president"
										<?php echo isset($post['type']) && $post['type'] == 'vice_president' ? 'selected="selected"' : ''; ?>>Vice President</option>
										
										<option value="treasurer"
										<?php echo isset($post['type']) && $post['type'] == 'treasurer' ? 'selected="selected"' : ''; ?>>Treasurer</option>
										
										<option value="member"
										<?php echo isset($post['type']) && $post['type'] == 'member' ? 'selected="selected"' : ''; ?>>Member</option>
									</select>
								</div>
								<div class="row">
									<div class="form-group col-md-3">
										<label for="member_age">Gender</label>
										<div class="radio">
											<label>
												<input type="radio" name="gender" value="male" 
												<?php echo isset($post['gender']) && $post['gender'] == 'male' ? 'checked="checked"' : ''; ?>
												<?php echo !isset($post['gender']) ? 'checked="checked"' : ''; ?>> Male
											</label>
										</div>
										<div class="radio">
											<label>
												<input type="radio" name="gender" value="female"
												<?php echo isset($post['gender']) && $post['gender'] == 'female' ? 'checked="checked"' : ''; ?>> Female
											</label>
										</div>
									</div>
									<div class="form-group col-md-9">
										<label for="member_age">Active</label>
										<div class="radio">
											<label>
												<input type="radio" name="active" value="1"
												<?php echo isset($post['active']) && $post['active'] == 1 ? 'checked="checked"' : ''; ?>
												<?php echo !isset($post['active']) ? 'checked="checked"' : ''; ?>> Active
											</label>
										</div>
										<div class="radio">
											<label>
												<input type="radio" name="active" value="0"
												<?php echo isset($post['active']) && $post['active'] == 0 ? 'checked="checked"' : ''; ?>> Inactive
											</label>
										</div>
									</div>
								</div>
								<div class="form-group">
									<input type="submit" class="btn btn-primary" name="add_member" value="Submit">
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>				
	</section>
</div>

<script type="text/javascript" src="/assets/scripts/cropper.js"></script>
<script type="text/javascript" src="/assets/cropper-master/examples/crop-avatar/js/crop-avatar.js"></script>