<div class="ministry-member-add-container">
	<section class="page-header ministry-header clearfix">
		<h2 class="pull-left">Add Member</h2>
		<a href="/ministry/<?php echo $ministry_id; ?>/members" class="btn btn-success pull-right"><i class="fa fa-th-list"></i>&nbsp; Back to Member List</a>
	</section>
	<section class="ministry-member-main container">
		<?php include(dirname(__FILE__).'/../_menu.phtml'); ?>

		<?php foreach ($errors as $error): ?>
			<div class="alert alert-danger"><?php echo $error; ?></div><br>
		<?php endforeach ?>

		<?php foreach ($msgs as $msg): ?>
			<div class="alert alert-<?php echo $msg['type']; ?>"><?php echo $msg['msg']; ?></div><br>
		<?php endforeach ?>
		
		<div class="panel panel-default">
			<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Member Profile Image</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12 clearfix">
						<div class="member-uploaded-images row">
							<div class="col-md-12 clearfix">
								<?php if (isset($_SESSION['member_tmpimages'])): ?>
									<?php foreach ($_SESSION['member_tmpimages'] as $key => $image): ?>
										<div class="upload-image">
											<div class="image-thumbnail">
												<img src="/uploads/member/<?php echo $image['file_name']; ?>">
											</div>
											<a href="/ministry/<?php echo $ministry_id; ?>/member/add?action=remove_upload&id=<?php echo $image['file_id']; ?>" 
											class="upload-actions remove-member-image" data-ids="<?php echo $image['file_id']; ?>">
												<i class="fa fa-times-circle fa-5x"></i>
											</a>
										</div>
									<?php endforeach ?>
								<?php endif ?>
							</div>
						</div>

						<form action="" method="post" enctype="multipart/form-data" id="event_images" class="event-images">
							<div class="upload-input-container">
								<div class="form-input">
								    <input name="file[]" type="file" />
								</div>
							</div>
						    <input type="submit" class="btn btn-info btn-sm" value="Upload Image" id="upload"/>
					    </form>
					</div>
				</div>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Create Member
			</div>
			<div class="panel-body">
				<form action="" method="post" class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label for="member_fullname">Full Name</label>
							<input type="text" name="fullname" id="ministry_fullname" class="form-control" placeholder="Member Full Name"
							value="<?php echo isset($post['fullname']) ? $post['fullname'] : ''; ?>">
						</div>
						<div class="form-group">
							<label for="member_email">Email</label>
							<input type="text" name="email" id="ministry_email" class="form-control" placeholder="Member Email" 
							value="<?php echo isset($post['email']) ? $post['email'] : ''; ?>">
						</div>
						<div class="form-group">
							<label for="member_phone">Phone</label>
							<input type="text" name="phone" id="ministry_phone" class="form-control" placeholder="Member Phone" 
							value="<?php echo isset($post['phone']) ? $post['phone'] : ''; ?>">
						</div>
						<div class="form-group">
							<label for="member_fullname">Address</label>
							<textarea name="address" class="form-control" cols="30" rows="5" placeholder="Member Address"><?php echo isset($post['address']) ? $post['address'] : ''; ?></textarea>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="member_age">Age</label>
							<input type="text" name="age" id="ministry_age" class="form-control" placeholder="Member Age" 
							value="<?php echo isset($post['age']) ? $post['age'] : ''; ?>">
						</div>
						<div class="form-group">
							<label for="member_age">Type</label>
							<select name="type" class="form-control">
								<option value="coordinator"
								<?php echo isset($post['type']) && $post['type'] == 'coordinator' ? 'selected="selected"' : ''; ?>>Coordinator</option>

								<option value="president"
								<?php echo isset($post['type']) && $post['type'] == 'president' ? 'selected="selected"' : ''; ?>>President</option>
								
								<option value="vice president"
								<?php echo isset($post['type']) && $post['type'] == 'vice_president' ? 'selected="selected"' : ''; ?>>Vice President</option>
								
								<option value="treasurer"
								<?php echo isset($post['type']) && $post['type'] == 'treasurer' ? 'selected="selected"' : ''; ?>>Treasurer</option>
								
								<option value="member"
								<?php echo isset($post['type']) && $post['type'] == 'member' ? 'selected="selected"' : ''; ?>>Member</option>
							</select>
						</div>
						<div class="row">
							<div class="form-group col-md-3">
								<label for="member_age">Gender</label>
								<div class="radio">
									<label>
										<input type="radio" name="gender" value="male" 
										<?php echo isset($post['gender']) && $post['gender'] == 'male' ? 'checked="checked"' : ''; ?>
										<?php echo !isset($post['gender']) ? 'checked="checked"' : ''; ?>> Male
									</label>
								</div>
								<div class="radio">
									<label>
										<input type="radio" name="gender" value="female"
										<?php echo isset($post['gender']) && $post['gender'] == 'female' ? 'checked="checked"' : ''; ?>> Female
									</label>
								</div>
							</div>
							<div class="form-group col-md-9">
								<label for="member_age">Active</label>
								<div class="radio">
									<label>
										<input type="radio" name="active" value="1"
										<?php echo isset($post['active']) && $post['active'] == 1 ? 'checked="checked"' : ''; ?>
										<?php echo !isset($post['active']) ? 'checked="checked"' : ''; ?>> Active
									</label>
								</div>
								<div class="radio">
									<label>
										<input type="radio" name="active" value="0"
										<?php echo isset($post['active']) && $post['active'] == 0 ? 'checked="checked"' : ''; ?>> Inactive
									</label>
								</div>
							</div>
						</div>
						<div class="form-group">
							<input type="submit" class="btn btn-primary" name="add_member" value="Submit">
						</div>
					</div>
				</form>
			</div>
		</div>
	</section>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('div.upload-image').hover(function(){
	    	$(this).find('a.remove-member-image').fadeToggle('fast');
	    });
	});
</script>