<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="http://lorempixel.com/1500/400/sports" />
            <div class="carousel-caption">
                <h1>SAMPLE CAROUSEL HEADER</h1>
                <p>Lorem Ipsum Dolor Sit Amet</p>
            </div>
        </div>
        <div class="item">
            <img src="http://lorempixel.com/1500/400/" />
            <div class="carousel-caption">
                <h1>SAMPLE CAROUSEL HEADER</h1>
                <p>Lorem Ipsum Dolor Sit Amet</p>
            </div>
        </div>
        <div class="item">
            <img src="http://lorempixel.com/1500/400/nature" />
            <div class="carousel-caption">
                <h1>SAMPLE CAROUSEL HEADER</h1>
                <p>Lorem Ipsum Dolor Sit Amet</p>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>