<section class="content-middle footer-container clearfix">
	<div class="footer-column contact">
		<h5>Contact Us</h5>

		<p class="contact-address">
			JESUS, LORD OF DIVINE MERCY PARISH Caimito St., Mapayapa Village I, Pasong Tamo 1107, Quezon City
		</p>
		
		<ul class="contact-numbers">
			<li>Tel: 931-4719</li>
			<li>Mobile: 09094448532</li>
			<li>E-mail: Divine_Mercy_Parish@yahoo.com</li>
		</ul>
	</div>

	<div class="footer-column quick-links">
		<h5>Quick Links</h5>
		
		<div class="clearfix">
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Ministries</a></li>
				<li><a href="#">Sermons</a></li>
				<li><a href="#">Events</a></li>
			</ul>

			<ul>
				<li><a href="#">Gallery</a></li>
				<li><a href="#">News</a></li>
				<li><a href="#">FAQS</a></li>
				<li><a href="#">Schedule</a></li>
				<li><a href="#">Store</a></li>
			</ul>
		</div>
	</div>

	<div class="footer-column follow">
		<h5>Follow Us</h5>

		<ul>
			<li><a href="#"><i class="fa fa-facebook"></i>&nbsp; Facebook</a></li>
			<li><a href="#"><i class="fa fa-twitter"></i>&nbsp; Twitter</a></li>
			<li><a href="#"><i class="fa fa-instagram"></i>&nbsp; Instagram</a></li>
			<li><a href="#"><i class="fa fa-google-plus"></i>&nbsp; Google Plus</a></li>
			<li><a href="#"><i class="fa fa-envelope"></i>&nbsp; Email</a></li>
		</ul>
	</div>

	<div class="footer-column newsletter">
		<h5>Subscribe to our Newsletter</h5>

		<form action="" method="post">
			<div class="form-group">
				<label for="newsletterName">Name*</label>
				<input type="text" class="form-control" id="newsletterName" placeholder="Name">
			</div>
			<div class="form-group">
				<label for="newsletterName">Email*</label>
				<input type="email" class="form-control" id="newsletterName" placeholder="Email">
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="Sign Up">
			</div>
		</form>
	</div>
</section>
<section class="footer-bottom">
	<div class="content-middle">
		<p>Copyright &copy; jldmp.com</p>
	</div>
</section>