<header class="main-header row">
	<div class="header-logo col-md-6">
		<h1>JLDMP</h1>
		<p>Jesus Lord of Divine Mercy Parish</p><br>
	</div>
	<nav class="main-navigation col-md-6">
		<ul class="nav nav-pills">
			<li class="active"><a href="#">Home</a></li>
			<li><a href="#">Ministry</a></li>
			<li><a href="#">Events</a></li>
			<li><a href="#">Schedule</a></li>
			<li class="btn-group">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Social <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#">Question and Answer</a></li>
					<li><a href="#">Chat</a></li>
				</ul>
			</li>
			<li class="btn-group">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Login <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#"><i class="fa fa-facebook"></i> Facebook</a></li>
					<li><a href="#"><i class="fa fa-twitter"></i> Twitter</a></li>
				</ul>
			</li>
		</ul>
	</nav>
</header>