<!DOCTYPE html>
<html class="<?php print $class; ?>">
	
<head>
	<title><?php print $title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<?php if(isset($meta) && is_array($meta)): ?>
    <?php foreach($meta as $name => $content): ?>
    <meta name="<?php print $name; ?>" content="<?php print $content; ?>" />
    <?php endforeach; ?>
    <?php endif; ?>

    <!-- montserrat and open sans fonts -->
	<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,500,600,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/bootstrap.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/datepicker3.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/front.css" />

    <link rel="stylesheet" type="text/css" href="/assets/styles/front/<?php echo $class; ?>.css">

    <script type="text/javascript" src="/assets/scripts/jquery.js"></script>
	<script type="text/javascript" src="/assets/scripts/jquery.form.js"></script>
	<script type="text/javascript" src="/assets/scripts/bootstrap.js"></script>
	<script type="text/javascript" src="/assets/scripts/bootstrap-datepicker.js"></script>
</head>

<body>
	<div class="page">
		<div class="head"><?php echo $head; ?></div>

		<?php if ($class == 'home'): ?>
			<div class="banner"><?php include(dirname(__FILE__).'/_banner.phtml'); ?></div>
		<?php endif ?>
		
		<div class="body"><?php echo $body; ?></div>
		<div class="foot"><?php echo $foot; ?></div>

		<script type="text/javascript" src="/assets/scripts/front.js"></script>
		<script type="text/javascript" src="/assets/scripts/front/<?php echo $class; ?>.js"></script>
		<script type="text/javascript" src="/assets/scripts/front.js"></script>
    </div>
</body>
</html>
