<section class="about-container">
	<section class="about-header">
		<div class="content-middle">

			<div class="header-wrap">
				<h3>About Us</h3>
				<ol class="breadcrumb">
					<li><a href="/">Home</a></li>
					<li class="active">About</li>
				</ol>
			</div>
		</div>
	</section>

	<div class="content-middle">
		<div class="clearfix about-content">
			<section class="about-main">
				<p class="main-description">
					Our church began the activity in 1995, and a lot has changed for us over the years but one thing has 
					remained consistent: a focus on helping people live in love for the Kingdom of God.
				</p>

				<p>
					Our building is situated on the street of Winsland, but our people represent a rich diversity 
					of ethnic, educational and socio-economic backgrounds.
				</p>

				<div class="mission">
					<h5>Our Mission:</h5>
					<blockquote>
						Our mission is to continually build a church that is relevant, constantly recognizes 
						and meets people’s needs, pursues the teaching of God’s Word and always provides an 
						atmosphere for positive relationships to grow and develop.
					</blockquote>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor 
						incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
						exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
					</p>
					<blockquote>
						Our mission is to continually build a church that is relevant, constantly recognizes 
						and meets people’s needs, pursues the teaching of God’s Word and always provides an 
						atmosphere for positive relationships to grow and develop.
					</blockquote>
					<p>
						Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium 
						doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore 
						veritatis et quasi architecto beatae vitae dicta sunt explicabo.
					</p>
					<p>
						Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
					</p>
					<p>
						Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?”
					</p>
				</div>
			</section>

			<section class="about-sidebar">
				<div class="sidebar-header clearfix">
					<h5>Events</h5>
					<a href="#" class="view-more">View More</a>
				</div>
			</section>
		</div>
	</div>
</section>