<div class="index-container">
	<section class="upcoming-event">
		<div class="content-middle clearfix">
			<div class="column first-column">
				<p class="event-label"><i class="fa fa-calendar"></i>&nbsp; Upcoming Event:</p>
				<p class="event-title">Sample Event Title</p>
			</div>
			<div class="column second-column clearfix">
				<ul class="event-countdown">
					<li>
						<span>10</span>
						<p>days</p>
					</li>
					<li>
						<span>09</span>
						<p>hours</p>
					</li>
					<li>
						<span>20</span>
						<p>minutes</p>
					</li>
					<li>
						<span>04</span>
						<p>seconds</p>
					</li>
				</ul>
				<div class="actions">
					<a href="#" class="join-now-btn">Join Now</a>
					<span>or</span>
					<a href="#" class="view-all">View all Events &nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-right"></i></a>
				</div>
			</div>
		</div>
	</section>
		
	<section class="index-main">
		<div class="first-row">
			<div class="content-middle clearfix">
				<section class="featured-ministries">
					<div class="list-header clearfix">
						<h4>Ministries</h4>
						<a href="#" class="view-more">View More</a>
					</div>
					<div class="ministry-list-container clearfix">
						<?php foreach ($ministries as $ministry): ?>
							<div class="ministry-template">
								<a class="ministry-image">
									<img src="/uploads/ministry/<?php echo $ministry['ministry_image']['file_name']; ?>" />
								</a>
								<a href="#" class="join-ministry"><i class="fa fa-plus"></i>&nbsp; Join</a>
								<div class="ministry-text">
									<p class="title"><?php echo $ministry['ministry_title']; ?></p>
									<p class="sub-title">
										<span class="members">10 Members</span> |
										<span class="events">5 Events</span>
									</p>
									<p class="description">
										<?php echo strlen($ministry['ministry_description']) > 100 ? substr($ministry['ministry_description'], 0, 100).'...' : $ministry['ministry_description']; ?>
									</p>
								</div>
								<div class="ministry-actions">
									<a href="#" class="view-details-btn"><i class="fa fa-long-arrow-right"></i>&nbsp; Read More</a>
								</div>
								<span class="bottom-bar"></span>
							</div>
						<?php endforeach ?>
					</div>
				</section>
				<section class="weekly-schedule">
					<div class="schedules-header">
						<h4>Weekly Mass Schedule</h4>
					</div>
					<ul class="schedule-list">
						<li>
							<span class="sched-label">Sunday Mass:</span>
							<span class="sched-time">
								Morning <br>
								7:00 am - 8:00 am <br>
								8:30 am - 9:30 am <br>
								10:00 am - 11:00 am <br><br>
								
								Evening <br>
								6:00 pm - 7:00 pm <br>
								7:30 pm - 8:30 pm
							</span>
						</li>
						<li>
							<span class="sched-label">Monday - Saturday Mass:</span>
							<span class="sched-time">6:00 pm - 7:00 pm</span>
						</li>
					</ul>
				</section>
			</div>
		</div>

		<div class="second-row index-quote">
			<div class="content-middle">
				<div class="index-quote-header clearfix">
					<h4>Bible Quotes</h4>
					<a href="#">View More</a>
				</div>

				<div id="bible-quote-carousel" class="carousel slide carousel-fade" data-ride="carousel">
					<!-- Indicators -->
				    <ol class="carousel-indicators">
				        <li data-target="#bible-quote-carousel" data-slide-to="0" class="active"></li>
				        <li data-target="#bible-quote-carousel" data-slide-to="1"></li>
				        <li data-target="#bible-quote-carousel" data-slide-to="2"></li>
				    </ol>

					<div class="carousel-inner">
						<div class="item active clearfix">
							<div class="quote-image">
								<img src="http://lorempixel.com/200/200/nature" alt="">
							</div>
							<div class="quote-text">
								<p class="title">"We all know that a church is not a building"</p>
								<p class="description">
									Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
								</p>
								<p class="author">Sample Author</p>
							</div>
						</div>
						<div class="item clearfix">
							<div class="quote-image">
								<img src="http://lorempixel.com/200/200" alt="">
							</div>
							<div class="quote-text">
								<p class="title">"For God did not send his Son into the world to condemn the world, but to save the world through him."</p>
								<p class="description">
									Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
								</p>
								<p class="author">Sample Author</p>
							</div>
						</div>
						<div class="item clearfix">
							<div class="quote-image">
								<img src="http://lorempixel.com/200/200/sports" alt="">
							</div>
							<div class="quote-text">
								<p class="title">"Love the Lord Your God with All Your Heart"</p>
								<p class="description">
									Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
								</p>
								<p class="author">Sample Author</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="index-menu">
		<div class="index-menu-content clearfix">
			<div class="column sermons">
				<h5>Sermons</h5>
				<p>
					Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
				</p>
				<a href="#" class="view-more">View More</a>
			</div>
			<div class="column gallery">
				<h5>News</h5>
				<p>
					Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
				</p>
				<a href="#" class="view-more">View More</a>
			</div>
			<div class="column social">
				<h5>Social</h5>
				<p>
					Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
				</p>
				<a href="#" class="view-more">View More</a>
			</div>
			<div class="column store">
				<h5>Store</h5>
				<p>
					Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
				</p>
				<a href="#" class="view-more">View More</a>
			</div>
		</div>
	</section>
	
	<section class="index-news">
		<div class="content-middle">
			<div class="news-header clearfix">
				<h4>Recent News</h4>
				<a href="#" class="view-more">View More</a>
			</div>
			<div class="news-row clearfix">
				<div class="news-column clearfix">
					<div class="news-image thumbnail">
						<img src="http://lorempixel.com/80/80/sports" alt="">
					</div>
					<div class="news-content">
						<p>Sample News Title</p>
						<span><i class="fa fa-calendar"></i>&nbsp; September 3, 2014</span>
					</div>
				</div>
				<div class="news-column clearfix">
					<div class="news-image thumbnail">
						<img src="http://lorempixel.com/80/80/abstract" alt="">
					</div>
					<div class="news-content">
						<p>Sample News Title</p>
						<span><i class="fa fa-calendar"></i>&nbsp; September 3, 2014</span>
					</div>
				</div>
				<div class="news-column clearfix">
					<div class="news-image thumbnail">
						<img src="http://lorempixel.com/80/80/city" alt="">
					</div>
					<div class="news-content">
						<p>Sample News Title</p>
						<span><i class="fa fa-calendar"></i>&nbsp; September 3, 2014</span>
					</div>
				</div>
				<div class="news-column clearfix">
					<div class="news-image thumbnail">
						<img src="http://lorempixel.com/80/80/people" alt="">
					</div>
					<div class="news-content">
						<p>Sample News Title</p>
						<span><i class="fa fa-calendar"></i>&nbsp; September 3, 2014</span>
					</div>
				</div>
			</div>
	</section>
</div>