<section class="index-content row">
	<div class="index-main-content col-md-9">
		<div class="page-header">
			<h2>Featured Events <small>come and join us!</small></h2>
		</div>

		<div class="index-event-list">
			<div class="index-event-item">
				<div class="event-title">
					<h4>Sample Event Title</h4>
					<p>
						<a href="#" class="event-author">Parish Youth Ministry</a>&nbsp;&nbsp;
						<span class="event-post">April 20</span>
					</p>
				</div>
				<div class="event-body row">
					<div class="event-img col-md-3">
						<img src="http://lorempixel.com/200/200/sports" width="200">
					</div>
					<div class="event-content col-md-9">
						<p>
							Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
						</p><br>
						<a href="#" class="event-read-more">Read More</a>
					</div>
				</div>
			</div>
		</div><hr>

		<div class="index-event-list">
			<div class="index-event-item">
				<div class="event-title">
					<h4>Sample Event Title</h4>
					<p>
						<a href="#" class="event-author">Parish Youth Ministry</a>&nbsp;&nbsp;
						<span class="event-post">April 20</span>
					</p>
				</div>
				<div class="event-body row">
					<div class="event-img col-md-3">
						<img src="http://lorempixel.com/200/200/" width="200">
					</div>
					<div class="event-content col-md-9">
						<p>
							Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
						</p><br>
						<a href="#" class="event-read-more">Read More</a>
					</div>
				</div>
			</div>
		</div><hr>

		<div class="index-event-list">
			<div class="index-event-item">
				<div class="event-title">
					<h4>Sample Event Title</h4>
					<p>
						<a href="#" class="event-author">Parish Youth Ministry</a>&nbsp;&nbsp;
						<span class="event-post">April 20</span>
					</p>
				</div>
				<div class="event-body row">
					<div class="event-img col-md-3">
						<img src="http://lorempixel.com/200/200/nature" width="200">
					</div>
					<div class="event-content col-md-9">
						<p>
							Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
						</p><br>
						<a href="#" class="event-read-more">Read More</a>
					</div>
				</div>
			</div>
		</div><hr>
	</div>
	<aside class="index-sidebar-snippets col-md-3">
		<form method="get" action="" class="index-search-form">
			<div class="input-group">
				<input type="text" class="form-control" placeholder="Search">
				<span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
			</div>
		</form>
	</aside>
</section><br>