<div class="ministries-container">
	<section class="background-header ministries">
		<div class="content-middle">

			<div class="header-wrap">
				<h3>Ministries</h3>
				<ol class="breadcrumb">
					<li><a href="/">Home</a></li>
					<li class="active">Ministries</li>
				</ol>
			</div>
		</div>
	</section>
	
	<section class="content-main">
		<div class="content-middle">
			<?php $i = 1; ?>
			<?php foreach ($ministries as $ministry): ?>
				<?php if ($i == 1): ?>
					<div class="ministry-list clearfix">
				<?php endif ?>

				<div class="ministry-template">
					<a href="/ministry/view/<?php echo $ministry['_id']->{'$id'} ?>" class="image">
						<img src="/uploads/ministry/<?php echo $ministry['ministry_image']['file_name']; ?>" alt="ministry image">
					</a>
					<a href="#" class="join-ministry"><i class="fa fa-plus"></i>&nbsp; Join</a>
					<div class="description">
						<p class="title">
							<a href="/ministry/view/<?php echo $ministry['_id']->{'$id'} ?>">
								<?php echo $ministry['ministry_title']; ?>
							</a>
						</p>
						<p class="sub-title">
							<span class="members">10 Members</span> |
							<span class="events">5 Events</span>
						</p>

						<p class="text">
							<?php echo strlen($ministry['ministry_description']) > 100 ? substr($ministry['ministry_description'], 0, 100).'...' : $ministry['ministry_description']; ?>
						</p>
					</div>
					<div class="actions">
						<a href="/ministry/view/<?php echo $ministry['_id']->{'$id'} ?>">Read More</a>
					</div>
					<span class="bottom-bar"></span>
				</div>

				<?php if ($i % 4 == 0): ?>
					<?php if ($i == count($ministries)): ?>
						</div>
					<?php else: ?>
						</div><div class="ministry-list clearfix">
					<?php endif ?>
				<?php endif ?>

				<?php $i++; ?>
			<?php endforeach ?>
		</div>
	</section>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		// $('.ministry-template').hover(function() {
		// 	$(this).find('.image img').css({ top : '-15px' });
		// });
	});
</script>