<div class="ministries-container">
	<section class="background-header ministries">
		<div class="content-middle">

			<div class="header-wrap">
				<h3>Ministries</h3>
				<ol class="breadcrumb">
					<li><a href="/">Home</a></li>
					<li class="active">Ministries</li>
				</ol>
			</div>
		</div>
	</section>

	<section class="content-middle content-main">
		<div class="ministry-list clearfix">
			<div class="ministry-template">
				<div class="image">
					<img src="/assets/images/placeholder.png" alt="ministry image">
				</div>
				<div class="description">
					<p class="title">Ministry of Altar Server</p>
					<p class="text">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					</p>
				</div>
				<div class="actions">
					<a href="#">Read More</a>
					<a href="#">Join</a>
				</div>
			</div>
			<div class="ministry-template">
				<div class="image">
					<img src="/assets/images/placeholder.png" alt="ministry image">
				</div>
				<div class="description">
					<p class="title">Ministry of Altar Server</p>
					<p class="text">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					</p>
				</div>
				<div class="actions">
					<a href="#">Read More</a>
					<a href="#">Join</a>
				</div>
			</div>
			<div class="ministry-template">
				<div class="image">
					<img src="/assets/images/placeholder.png" alt="ministry image">
				</div>
				<div class="description">
					<p class="title">Ministry of Altar Server</p>
					<p class="text">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					</p>
				</div>
				<div class="actions">
					<a href="#">Read More</a>
					<a href="#">Join</a>
				</div>
			</div>
			<div class="ministry-template">
				<div class="image">
					<img src="/assets/images/placeholder.png" alt="ministry image">
				</div>
				<div class="description">
					<p class="title">Ministry of Altar Server</p>
					<p class="text">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					</p>
				</div>
				<div class="actions">
					<a href="#">Read More</a>
					<a href="#">Join</a>
				</div>
			</div>
		</div>

		<div class="ministry-list clearfix">
			<div class="ministry-template">
				<div class="image">
					<img src="/assets/images/placeholder.png" alt="ministry image">
				</div>
				<div class="description">
					<p class="title">Ministry of Altar Server</p>
					<p class="text">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					</p>
				</div>
				<div class="actions">
					<a href="#">Read More</a>
					<a href="#">Join</a>
				</div>
			</div>
		</div>
	</section>
</div>