<link rel="stylesheet" href="/assets/styles/cropper.css">
<link rel="stylesheet" href="/assets/cropper-master/examples/crop-avatar/css/crop-avatar.css">

<div class="add-ministry-container container" id="crop-avatar">
	<section class="page-header ministry-header row">
		<div class="col-md-12 clearfix">
			<h2 class="pull-left">Add Ministry <small>Settings</small></h2>
			<a href="/ministries" class="btn btn-success pull-right"><i class="fa fa-th-list"></i>&nbsp; Back to List</a>
		</div>
	</section>
	<section class="add-ministry-main clearfix">

		<?php foreach ($errors as $error): ?>
			<div class="alert alert-danger"><?php echo $error; ?></div><br>
		<?php endforeach ?>
		
		<?php include(dirname(__FILE__).'/../_msg.phtml'); ?>
	
		<div class="row">
			<div class="col-md-3">
				<div class="panel panel-default">
					<div class="panel-heading"><i class="glyphicon glyphicon-info-sign"></i>&nbsp; Update ministry</div>
					<div class="panel-body">
						<div class="ministry-image avatar-view" title="Upload Ministry Image">
							<?php if (!empty($_SESSION['ministry_tmpimage'])): ?>
								<img src="/uploads/ministry/<?php echo $_SESSION['ministry_tmpimage']['file_name']; ?>">
							<?php else: ?>
								<img src="/assets/images/placeholder.png">
							<?php endif ?>

							<span class="btn btn-success btn-sm">
								<i class="fa fa-image"></i>&nbsp; Upload News Photo
							</span>
						</div>

						<div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
							<div class="modal-dialog modal-lg">
								<div class="modal-content">
									<form class="avatar-form" method="post" action="" enctype="multipart/form-data">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal">&times;</button>
											<h4 class="modal-title" id="avatar-modal-label">Change Avatar</h4>
										</div>
										<div class="modal-body">
											<div class="avatar-body">
												<!-- Upload image and data -->
												<div class="avatar-upload">
													<input class="avatar-src" name="avatar_src" type="hidden">
													<input class="avatar-data" name="avatar_data" type="hidden">
													<label for="avatarInput">Local upload</label>
													<input class="avatar-input" id="avatarInput" name="file" type="file">
												</div>

												<!-- Crop and preview -->
												<div class="row">
													<div class="col-md-9">
														<div class="avatar-wrapper"></div>
													</div>
													<div class="col-md-3">
														<div class="avatar-preview preview-lg"></div>
														<div class="avatar-preview preview-md"></div>
														<div class="avatar-preview preview-sm"></div>
													</div>
												</div>
											</div>
										</div>
										<div class="modal-footer">
											<button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
											<button class="btn btn-primary avatar-save" type="submit">Save</button>
										</div>
									</form>
								</div>
							</div>
						</div><!-- /.modal -->							
					</div>
				</div>
			</div>
			<div class="col-md-9">
				<div class="panel panel-default">
					<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Ministry Information</div>
					<div class="panel-body">
						<form action="" method="post" class="add-ministry-form clearfix">
							<div class="ministry-form-settings col-md-6 pull-left">
								<h4>Ministry Settings</h4><br>
								<div class="form-group">
									<label for="ministry_title">Title</label>
									<input type="text" name="title" id="ministry_title" class="form-control" placeholder="Ministry Title"
									value="<?php echo isset($post['title']) ? $post['title'] : ''; ?>">
								</div>
								<div class="form-group">
									<label for="ministry_description">Description</label>
									<textarea name="description" id="ministry_description" class="form-control" placeholder="Ministry Description.."><?php echo isset($post['description']) ? $post['description'] : ''; ?></textarea>
								</div>
								<div class="form-group">
									<label>Active</label>
									<div class="input-active">
										<label for="ministry_active_yes" class="radio-inline">
											<input type="radio" name="active" class="ministry-active" value="1"  id="ministry_active_yes" 
											<?php echo (isset($post['active']) && $post['active'] == 1) ? 'checked' : ''; ?>>Yes
										</label>
										<label for="ministry_active_no" class="radio-inline">
											<input type="radio" name="active" class="ministry-active" value="0" id="ministry_active_no"
											<?php echo (isset($post['active']) && $post['active'] == 0) ? 'checked' : ''; ?>>No
										</label>
									</div>
								</div>
							</div>
							<div class="admin-form-settings col-md-6 pull-left">
								<h4>Admin Settings</h4><br>
								<div class="form-group">
									<label for="admin_name">Name</label>
									<input type="text" name="name" id="admin_name" class="form-control" placeholder="Name"
									value="<?php echo isset($post['name']) ? $post['name'] : ''; ?>">
								</div>
								<div class="form-group">
									<label for="admin_email">Email</label>
									<input type="text" name="email" id="admin_email" class="form-control" placeholder="Email"
									value="<?php echo isset($post['email']) ? $post['email'] : ''; ?>">
								</div>
								<div class="form-group">
									<label for="admin_username">Username</label>
									<input type="text" name="username" id="admin_username" class="form-control" placeholder="Username"
									value="<?php echo isset($post['username']) ? $post['username'] : ''; ?>">
								</div>
								<div class="form-group">
									<label for="admin_password">Password</label>
									<input type="password" name="password" id="admin_password" class="form-control" placeholder="Password"
									value="<?php echo isset($post['password']) ? $post['password'] : ''; ?>">
								</div>
								<div class="form-group">
									<label for="admin_confirm">Confirm Password</label>
									<input type="password" name="confirm" id="admin_confirm" class="form-control" placeholder="Confirm"
									value="<?php echo isset($post['confirm']) ? $post['confirm'] : ''; ?>">
								</div>
								<div class="form-group">
									<button type="submit" class="btn btn-info" name="add_ministry" value="submit"><i class="fa fa-check-square-o"></i>&nbsp; Submit</button>&nbsp;&nbsp;
									<span class="js-error-msg"></span>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>	
</div>

<script type="text/javascript" src="/assets/scripts/cropper.js"></script>
<script type="text/javascript" src="/assets/cropper-master/examples/crop-avatar/js/crop-avatar.js"></script>