<link rel="stylesheet" href="/assets/styles/cropper.css">
<link rel="stylesheet" href="/assets/cropper-master/examples/crop-avatar/css/crop-avatar.css">

<div class="edit-ministry-container">
	<section class="page-header ministry-header clearfix">
		<h2 class="pull-left">Edit Ministry <small>Settings</small></h2>
		<a href="/ministries" class="btn btn-success pull-right"><i class="fa fa-th-list"></i>&nbsp; Back to List</a>
	</section>
	<section class="edit-ministry-main clearfix">
		<?php foreach ($errors as $error): ?>
			<div class="alert alert-danger"><?php echo $error; ?></div><br>
		<?php endforeach ?>

		<?php include(dirname(__FILE__).'/../_msg.phtml'); ?>

		<div class="row">
			<div class="col-md-3">
				<div class="panel panel-default">
					<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Ministry Images</div>
					<div class="panel-body" id="crop-avatar">
						<div class="ministry-image avatar-view" title="Upload News Image">
							<?php if (!empty($post['ministry_image'])): ?>
								<img src="/uploads/ministry/<?php echo $post['ministry_image']['file_name']; ?>">
							<?php else: ?>
								<img src="/assets/images/placeholder.png">
							<?php endif ?>

							<span class="btn btn-success btn-sm">
								<i class="fa fa-image"></i>&nbsp; Update Ministry Photo
							</span>
						</div>

						<div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
							<div class="modal-dialog modal-lg">
								<div class="modal-content">
									<form class="avatar-form" method="post" action="" enctype="multipart/form-data">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal">&times;</button>
											<h4 class="modal-title" id="avatar-modal-label">Change Avatar</h4>
										</div>
										<div class="modal-body">
											<div class="avatar-body">
												<!-- Upload image and data -->
												<div class="avatar-upload">
													<input class="avatar-src" name="avatar_src" type="hidden">
													<input class="avatar-data" name="avatar_data" type="hidden">
													<label for="avatarInput">Local upload</label>
													<input class="avatar-input" id="avatarInput" name="file" type="file">
												</div>

												<!-- Crop and preview -->
												<div class="row">
													<div class="col-md-9">
														<div class="avatar-wrapper"></div>
													</div>
													<div class="col-md-3">
														<div class="avatar-preview preview-lg"></div>
														<div class="avatar-preview preview-md"></div>
														<div class="avatar-preview preview-sm"></div>
													</div>
												</div>
											</div>
										</div>
										<div class="modal-footer">
											<button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
											<button class="btn btn-primary avatar-save" type="submit">Save</button>
										</div>
									</form>
								</div>
							</div>
						</div><!-- /.modal -->
					</div>
				</div>
			</div>
			<div class="col-md-9">
				<div class="panel panel-default">
					<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Ministry Information</div>
					<div class="panel-body">
						<form action="" method="post" class="edit-ministry-form clearfix">
							<div class="row">
								<div class="ministry-form-settings col-md-6">
									<h4>Ministry Information</h4><br>
									<input type="hidden" name="ministry_id" value="<?php echo $post['_id']->{'$id'}; ?>">
									<div class="form-group">
										<label for="ministry_title">Title</label>
										<input type="text" name="ministry_title" id="ministry_title" class="form-control" placeholder="Ministry Title"
										value="<?php echo isset($post['ministry_title']) ? $post['ministry_title'] : ''; ?>">
									</div>
									<div class="form-group">
										<label for="ministry_description">Description</label>
										<textarea name="ministry_description" id="ministry_description" class="form-control" placeholder="Ministry Description.."><?php echo isset($post['ministry_description']) ? $post['ministry_description'] : ''; ?></textarea>
									</div>
									<div class="form-group">
										<label>Active</label>
										<div class="input-active">
											<label for="ministry_active_yes" class="radio-inline">
												<input type="radio" name="ministry_active" class="ministry-active" value="1" id="ministry_active_yes" 
												<?php echo (isset($post['ministry_active']) && $post['ministry_active'] == 1) ? 'checked' : ''; ?>>Yes
											</label>
											<label for="ministry_active_no" class="radio-inline">
												<input type="radio" name="ministry_active" class="ministry-active" value="0" id="ministry_active_no"
												<?php echo (isset($post['ministry_active']) && $post['ministry_active'] == 0) ? 'checked' : ''; ?>>No
											</label>
										</div>
									</div>
								</div>
								<div class="admin-form-settings col-md-6">
									<h4>Admin Settings</h4><br>
									<input type="hidden" name="admin_id" value="<?php echo $post['admin']['_id']->{'$id'}; ?>">
									<div class="form-group">
										<label for="admin_name">Name</label>
										<input type="text" name="admin_name" id="admin_name" class="form-control" placeholder="Name"
										value="<?php echo isset($post['admin']['admin_name']) ? $post['admin']['admin_name'] : ''; ?>">
									</div>
									<div class="form-group">
										<label for="admin_email">Email</label>
										<input type="text" name="admin_email" id="admin_email" class="form-control" placeholder="Email"
										value="<?php echo isset($post['admin']['admin_email']) ? $post['admin']['admin_email'] : ''; ?>">
									</div>
									<div class="form-group">
										<label for="admin_username">Username</label>
										<input type="text" name="admin_username" id="admin_username" class="form-control" placeholder="Username"
										value="<?php echo isset($post['admin']['admin_username']) ? $post['admin']['admin_username'] : ''; ?>">
									</div>
									<div class="form-group">
										<button type="submit" class="btn btn-info" name="edit_ministry" value="submit"><i class="fa fa-check-square-o"></i>&nbsp; Submit</button>&nbsp;&nbsp;
										<span class="js-error-msg"></span>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

<script type="text/javascript" src="/assets/scripts/cropper.js"></script>
<script type="text/javascript" src="/assets/cropper-master/examples/crop-avatar/js/crop-avatar.js"></script>