<div class="edit-ministry-container">
	<section class="page-header ministry-header clearfix">
		<h2 class="pull-left">Edit Ministry <small>Settings</small></h2>
		<a href="/ministry" class="btn btn-success pull-right"><i class="fa fa-th-list"></i>&nbsp; Back to List</a>
	</section>
	<section class="edit-ministry-main clearfix">
		<?php foreach ($errors as $error): ?>
			<div class="alert alert-danger"><?php echo $error; ?></div><br>
		<?php endforeach ?>

		<?php include(dirname(__FILE__).'/../_msg.phtml'); ?>

		<div class="panel panel-default">
			<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Ministry Image</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-3">
						<div class="ministry-uploaded-images clearfix">
							<div class="upload-image">
								<div class="image-thumbnail">
									<?php if (isset($post['ministry_image']) && !empty($post['ministry_image'])): ?>
										<img src="/uploads/ministry/<?php echo $post['ministry_image']['file_name']; ?>">
									<?php else: ?>
										<img src="/assets/images/placeholder.png">
									<?php endif ?>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-9">
						<form action="" method="post" enctype="multipart/form-data" id="ministry_images_form" class="ministry-images-form">
							<div class="upload-input-container">
								<div class="form-input">
								    <input name="file[]" type="file" />
								</div>
							</div>
						    
						    <input type="submit" class="btn btn-info btn-sm" 
						    value="Update Image" id="upload"/>

						    <?php if (isset($post['ministry_image']) && !empty($post['ministry_image'])): ?>
							    <a href="/ministry/edit/<?php echo $post['_id']->{'$id'}; ?>?action=remove_image&id=<?php echo $post['ministry_image']['_id']->{'$id'}; ?>"
							    class="remove-image-btn btn btn-danger btn-sm">
									<i class="fa fa-times-circle"></i>&nbsp; Remove Image
							    </a>
						    <?php endif ?>
					    </form>
					</div>
				</div>
			</div>
		</div>
		
		<div class="panel panel-default">
			<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Ministry Information</div>
			<div class="panel-body">
				<form action="" method="post" class="edit-ministry-form clearfix">
					<div class="ministry-form-settings col-md-6">
						<h4>Ministry Information</h4><br>
						<input type="hidden" name="ministry_id" value="<?php echo $post['_id']->{'$id'}; ?>">
						<div class="form-group">
							<label for="ministry_title">Title</label>
							<input type="text" name="ministry_title" id="ministry_title" class="form-control" placeholder="Ministry Title"
							value="<?php echo isset($post['ministry_title']) ? $post['ministry_title'] : ''; ?>">
						</div>
						<div class="form-group">
							<label for="ministry_description">Description</label>
							<textarea name="ministry_description" id="ministry_description" class="form-control" placeholder="Ministry Description.."><?php echo isset($post['ministry_description']) ? $post['ministry_description'] : ''; ?></textarea>
						</div>
						<div class="form-group">
							<label>Active</label>
							<div class="input-active">
								<label for="ministry_active_yes" class="radio-inline">
									<input type="radio" name="ministry_active" class="ministry-active" value="1" id="ministry_active_yes" 
									<?php echo (isset($post['ministry_active']) && $post['ministry_active'] == 1) ? 'checked' : ''; ?>>Yes
								</label>
								<label for="ministry_active_no" class="radio-inline">
									<input type="radio" name="ministry_active" class="ministry-active" value="0" id="ministry_active_no"
									<?php echo (isset($post['ministry_active']) && $post['ministry_active'] == 0) ? 'checked' : ''; ?>>No
								</label>
							</div>
						</div>
					</div>
					<div class="admin-form-settings col-md-6">
						<h4>Admin Settings</h4><br>
						<input type="hidden" name="admin_id" value="<?php echo $post['admin']['_id']->{'$id'}; ?>">
						<div class="form-group">
							<label for="admin_name">Name</label>
							<input type="text" name="admin_name" id="admin_name" class="form-control" placeholder="Name"
							value="<?php echo isset($post['admin']['admin_name']) ? $post['admin']['admin_name'] : ''; ?>">
						</div>
						<div class="form-group">
							<label for="admin_email">Email</label>
							<input type="text" name="admin_email" id="admin_email" class="form-control" placeholder="Email"
							value="<?php echo isset($post['admin']['admin_email']) ? $post['admin']['admin_email'] : ''; ?>">
						</div>
						<div class="form-group">
							<label for="admin_username">Username</label>
							<input type="text" name="admin_username" id="admin_username" class="form-control" placeholder="Username"
							value="<?php echo isset($post['admin']['admin_username']) ? $post['admin']['admin_username'] : ''; ?>">
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-info" name="edit_ministry" value="submit"><i class="fa fa-check-square-o"></i>&nbsp; Submit</button>&nbsp;&nbsp;
							<span class="js-error-msg"></span>
						</div>
					</div>
				</form>
			</div>
		</div>
	</section>
</div>