<div class="ministry-member-container">
	<ol class="breadcrumb">
		<li><a href="/">Home</a></li>
		<li><a href="/ministry">Ministry List</a></li>
		<li class="active">Members</li>
	</ol>

	<section class="page-header ministry-header clearfix">
		<h2 class="pull-left">Members</h2>

		<div class="page-header-actions pull-right">
			<a href="/ministry" class="btn btn-success"><i class="fa fa-th-list"></i>&nbsp; Back to Ministry List</a>
			<a href="/ministry/<?php echo $ministry_id; ?>/member/add" class="btn btn-info">
				<i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Add Member
			</a>
		</div>
	</section>

	<section class="ministry-member-main container">
		<?php include(dirname(__FILE__).'/_menu.phtml'); ?>
		
		<div class="row">
			<div class="col-md-3">
				<div class="list-group">
					<a href="/ministry/<?php echo $ministry_id; ?>/members" class="list-group-item
					<?php echo $var == null ? 'active' : ''; ?>">
						<i class="fa fa-th-list"></i>&nbsp; All
					</a>
					<a href="/ministry/<?php echo $ministry_id; ?>/members/active" class="list-group-item
					<?php echo $var == 'active' ? 'active' : ''; ?>">
						<i class="glyphicon glyphicon-ok"></i>&nbsp; Active
					</a>
					<a href="/ministry/<?php echo $ministry_id; ?>/members/not-active" class="list-group-item
					<?php echo $var == 'not-active' ? 'active' : ''; ?>">
						<i class="glyphicon glyphicon-remove"></i>&nbsp; Not Active
					</a>
					<a href="/ministry/<?php echo $ministry_id; ?>/members/request" class="list-group-item
					<?php echo $var == 'request' ? 'active' : ''; ?>">
						<i class="glyphicon glyphicon-minus"></i>&nbsp; Request
					</a>
				</div>
			</div>
			<div class="col-md-9">
				<?php foreach ($msg as $m): ?>
					<div class="alert alert-<?php echo $m['type']; ?>"><?php echo $m['msg']; ?></div>
				<?php endforeach ?>

				<div class="row">
					<form action="" method="get" class="search-member-form col-md-5">
						 <div class="input-group">
							<input type="text" name="q" class="form-control" placeholder="Search Member" 
							value="<?php echo isset($_GET['q']) ? $_GET['q'] : ''; ?>" <?php echo isset($_GET['q']) ? 'autofocus' : ''; ?>>
							<span class="input-group-btn">
								<input type="submit" class="btn btn-warning" value="Search">
							</span>
						</div>
					</form>
					<div class="col-md-7">
						<ul class="pagination pagination-sm pull-right">
							<?php $range = $pg+5; $start = $range - 10; ?>
							<?php $start = $start < 1 ? 1 : $start; ?>
							<?php for($i = $start; $i <= $pages; $i++): ?>
								<li<?php echo $i == $pg ? ' class="active"' : NULL; ?>>
									<a href="?page=<?php echo $i; ?><?php echo isset($_GET['q']) && $_GET['q'] ? '&q='.$_GET['q'] : ''; ?>">
										<?php echo $i; ?>
									</a>
								</li>
								<?php if($range == $i) break; ?>
							<?php endfor; ?>
						</ul>
					</div>
				</div>
				<br>
				<table class="table table-striped table-bordered">
					<thead>
						<th>ID</th>
						<th>Image</th>
						<th>Name</th>
						<th>Active</th>
						<th>Type</th>
						<th>Actions</th>
					</thead>
					<tbody>
						<?php if (!empty($members)): ?>
							<?php foreach ($members as $member): ?>
								<tr>
									<td><?php echo $member['_id']->{'$id'}; ?></td>
									<td>
										<div class="thumbnail">
											<?php if (!empty($member['member_image'])): ?>
												<img src="/uploads/member/<?php echo $member['member_image']['file_name']; ?>" width="50">
											<?php else: ?>
												<img src="/assets/images/placeholder.png" width="50">
											<?php endif ?>
										</div>
									</td>
									<td>
										<?php echo ucwords($member['member_fullname']); ?>
									</td>
									<td>
										<?php 
											switch ($member['member_active']) {
												case 0: $active = 'not-active'; $label = 'red'; break;
												case 1: $active = 'active'; $label = 'green'; break;
												case 2: $active = 'request'; $label = 'orange'; break;
											}
										 ?>
										<span class="<?php echo $label; ?>"><?php echo ucfirst($active); ?></span>
									</td>
									<td><?php echo $member['member_type']; ?></td>
									<td>
										<a href="/ministry/<?php echo $ministry_id; ?>/member/view/<?php echo $member['_id']->{'$id'}; ?>" class="btn btn-info btn-xs">
											<i class="fa fa-share"></i>&nbsp; View
										</a>

										<a href="/ministry/<?php echo $ministry_id; ?>/member/edit/<?php echo $member['_id']->{'$id'}; ?>" class="btn btn-info btn-xs">
											<i class="fa fa-pencil-square"></i>&nbsp; Edit
										</a>

										<a href="/ministry/<?php echo $ministry_id; ?>/members?action=deleteMember&id=<?php echo $member['_id']->{'$id'} ?>"
										class="btn btn-info btn-xs remove-member">
											<i class="fa fa-times-circle"></i>&nbsp; Remove
										</a>
									</td>
								</tr>
							<?php endforeach ?>
						<?php else: ?>
							<tr><td colspan="6">No members returned</td></tr>
						<?php endif ?>
					</tbody>
				</table>
				<div class="row">
					<div class="col-md-12">
						<ul class="pagination pagination-sm pull-right">
							<?php $range = $pg+5; $start = $range - 10; ?>
							<?php $start = $start < 1 ? 1 : $start; ?>
							<?php for($i = $start; $i <= $pages; $i++): ?>
								<li<?php echo $i == $pg ? ' class="active"' : NULL; ?>>
									<a href="?page=<?php echo $i; ?><?php echo isset($_GET['q']) && $_GET['q'] ? '&q='.$_GET['q'] : ''; ?>">
										<?php echo $i; ?>
									</a>
								</li>
								<?php if($range == $i) break; ?>
							<?php endfor; ?>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
