<div class="ministry-news-container">
	<ol class="breadcrumb">
		<li><a href="/">Home</a></li>
		<li><a href="/ministries">Ministry List</a></li>
		<li class="active">News</li>
	</ol>

	<section class="page-header ministry-header clearfix">
		<h2 class="pull-left">News <small>settings</small></h2>

		<div class="page-header-actions pull-right">
			<a href="/ministries" class="btn btn-success"><i class="fa fa-th-list"></i>&nbsp; Back to Ministry List</a>
			<a href="/ministry/<?php echo $ministry_id; ?>/news/add" class="btn btn-info">
				<i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Add News
			</a>
		</div>
	</section>

	<section class="ministry-event-main container">
		<?php include(dirname(__FILE__).'/_menu.phtml'); ?>
		
		<div class="row">
			<div class="col-md-3">
				<div class="list-group">
					<a href="/ministry/<?php echo $ministry_id; ?>/news" class="list-group-item
					<?php echo $var == null ? 'active' : ''; ?>">
						<i class="fa fa-th-list"></i>&nbsp; All
					</a>
					<a href="/ministry/<?php echo $ministry_id; ?>/news/active" class="list-group-item
					<?php echo $var == 'active' ? 'active' : ''; ?>">
						<i class="glyphicon glyphicon-ok"></i>&nbsp; Active
					</a>
					<a href="/ministry/<?php echo $ministry_id; ?>/news/not-active" class="list-group-item
					<?php echo $var == 'not-active' ? 'active' : ''; ?>">
						<i class="glyphicon glyphicon-remove"></i>&nbsp; Not Active
					</a>
				</div>
			</div>
			<div class="col-md-9">
				<?php foreach ($msg as $m): ?>
					<div class="alert alert-<?php echo $m['type']; ?>"><?php echo $m['msg']; ?></div>
				<?php endforeach ?>
				
				<div class="row">
					<form action="" method="get" class="search-news-form col-md-5">
						 <div class="input-group">
							<input type="text" name="q" class="form-control" placeholder="Search News" 
							value="<?php echo isset($_GET['q']) ? $_GET['q'] : ''; ?>" <?php echo isset($_GET['q']) ? 'autofocus' : ''; ?>>

							<span class="input-group-btn">
								<input type="submit" class="btn btn-warning" value="Search">
							</span>
						</div>
					</form>
					<div class="col-md-7">
						<ul class="pagination pagination-sm pull-right">
							<?php $range = $pg+5; $start = $range - 10; ?>
							<?php $start = $start < 1 ? 1 : $start; ?>
							<?php for($i = $start; $i <= $pages; $i++): ?>
								<li<?php echo $i == $pg ? ' class="active"' : NULL; ?>>
									<a href="?page=<?php echo $i; ?><?php echo isset($_GET['q']) && $_GET['q'] ? '&q='.$_GET['q'] : ''; ?>">
										<?php echo $i; ?>
									</a>
								</li>
								<?php if($range == $i) break; ?>
							<?php endfor; ?>
						</ul>
					</div>
				</div>
				<br>
				<table class="table table-striped table-bordered">
					<thead>
						<th>ID</th>
						<th>Image</th>
						<th>Title</th>
						<th>News Updated</th>
					</thead>
					<tbody>
						<?php if (!empty($news)): ?>
							<?php foreach ($news as $item): ?>
								<tr>
									<td><?php echo $item['_id']->{'$id'}; ?></td>
									<td>
										<div class="thumbnail">
											<?php if (!empty($item['news_image'])): ?>
												<img src="/uploads/news/<?php echo $item['news_image']['file_name']; ?>" width="80">
											<?php else: ?>
												<img src="/assets/images/placeholder.png" width="80">
											<?php endif ?>
										</div>
									</td>
									<td class="table-actions">
										<?php 
											switch ($item['news_active']) {
												case 0:	$active = 'not-active'; $label = 'red'; break;
												case 1:	$active = 'active'; $label = 'green'; break;
											}
										 ?>
										<strong><?php echo $item['news_title']; ?></strong><hr>

										<div>
											<span class="<?php echo $label; ?>"><strong><?php echo $active; ?></strong></span> |
											<a href="/ministry/<?php echo $ministry_id; ?>/news/view/<?php echo $item['_id']->{'$id'}; ?>" class="news-action-btn">
												<i class="fa fa-share"></i>&nbsp; View
											</a> |
											<a href="/ministry/<?php echo $ministry_id; ?>/news/edit/<?php echo $item['_id']->{'$id'}; ?>" class="news-action-btn">
												<i class="fa fa-pencil-square"></i>&nbsp; Edit
											</a> |
											<a href="/ministry/<?php echo $ministry_id; ?>/news?action=remove_news&id=<?php echo $item['_id']->{'$id'}; ?>"
											class="event-action-btn remove-event">
												<i class="fa fa-times-circle"></i>&nbsp; Remove
											</a>
										</div>
									</td>
									<td><?php echo date('Y-m-d', $item['news_updated']->sec); ?></td>
								</tr>
							<?php endforeach ?>
						<?php else: ?>
							<tr><td colspan="4">No news returned.</td></tr>
						<?php endif ?>
					</tbody>
				</table>
			</div>
		</div>
	</section>
</div><br>
