<div class="ministry-event-view-container">
	<section class="page-header ministry-header clearfix">
		<h2 class="pull-left">Event Detail</h2>
		<a href="/ministry/<?php echo $ministry_id; ?>/events" class="btn btn-success pull-right"><i class="fa fa-th-list"></i>&nbsp; Back to Events List</a>
	</section>
	<section class="ministry-event-view-main container">
		<?php include(dirname(__FILE__).'/../_menu.phtml'); ?>

		<?php foreach ($msgs as $msg): ?>
			<div class="alert alert-<?php echo $msg['type']; ?>"><?php echo $msg['msg']; ?></div><br>
		<?php endforeach ?>
			
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="glyphicon glyphicon-info-sign"></i>&nbsp; Event Information
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12 clearfix">
				        <label for="event_images">Event Images</label>
						<div class="event-uploaded-images row">
							<div class="col-md-12 clearfix">
								<?php if (!empty($event['event_images'])): ?>
									<?php foreach ($event['event_images'] as $key => $image): ?>
										<div class="upload-image">
											<div class="image-thumbnail">
												<img src="/uploads/event/<?php echo $image['file_name']; ?>">
											</div>
										</div>
									<?php endforeach ?>
								<?php endif ?>
							</div>
						</div>
					</div>
				</div><hr>
				<div class="row">
					<div class="col-md-12">
						<h3><?php echo $event['event_title']; ?></h3><br>
						<p><?php echo $event['event_text']; ?></p>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>