<div class="ministry-event-view-container">
	<section class="page-header ministry-header clearfix">
		<h2 class="pull-left">Event Detail</h2>
		<a href="/ministry/<?php echo $ministry_id; ?>/events" class="btn btn-success pull-right"><i class="fa fa-th-list"></i>&nbsp; Back to Events List</a>
	</section>
	<section class="ministry-event-view-main">
		<?php include(dirname(__FILE__).'/../_menu.phtml'); ?>

		<?php include(dirname(__FILE__).'/../../_msg.phtml'); ?>

		<div class="row">
			<div class="col-md-3">
				<div class="panel panel-default">
					<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Event Image</div>
					<div class="panel-body" id="crop-avatar">
						<div class="news-image avatar-view" title="Upload News Image">
							<?php if (!empty($event['event_image'])): ?>
								<img src="/uploads/event/<?php echo $event['event_image']['file_name']; ?>">
							<?php else: ?>
								<img src="/assets/images/placeholder.png">
							<?php endif ?>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-9">
				<div class="panel panel-default">
					<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Event Image</div>
					<div class="panel-body">
						<h3><?php echo $event['event_title']; ?></h3><br>
						<p><?php echo $event['event_text']; ?></p>
						<p><?php echo date('F j, Y', $event['event_start']); ?> - <?php echo date('F j, Y', $event['event_end']); ?></p>
					</div>
				</div>
			</div>
		</div>			
	</section>
</div>