<div class="ministry-container" id="main">
	<section class="ministry-info content-middle">
		<div class="info-main clearfix">
			<div class="ministry-image">
				<img src="/uploads/ministry/<?php echo $ministry['ministry_image']['file_name']; ?>" alt="ministry image">
			</div>
			<div class="ministry-description">
				<h3><?php echo ucwords($ministry['ministry_title']); ?></h3>
				<div class="coordinator">
					<p class="admin">
						<i class="glyphicon glyphicon-user"></i>&nbsp; Coordinator:
						<?php echo $ministry['ministry_admin']['admin_name']; ?>
					</p>
					<p class="email">
						<i class="glyphicon glyphicon-envelope"></i>&nbsp; Email:
						<?php echo $ministry['ministry_admin']['admin_email']; ?>
					</p>
				</div>
				<div class="text">
					<p><?php echo $ministry['ministry_description']; ?></p>
				</div>
				<div class="actions">
					<a href="#" class="join-ministry"><i class="fa fa-plus"></i>&nbsp; Join</a>
				</div>
			</div>
		</div>
	</section>

	<section class="content-main">
		<div class="content-wrapper content-middle clearfix">
			<section class="left-panel panel">
				<div class="header">
					<ul class="ministry-menu">
						<li class="<?php echo $class == 'view' ? 'active' : ''; ?>">
							<a href="/ministry/view/<?php echo $ministry['_id']->{'$id'}; ?>#main">Members</a>
						</li>
						<li class="<?php echo $class == 'events' ? 'active' : ''; ?>">
							<a href="/ministry/<?php echo $ministry['_id']->{'$id'}; ?>/events#main">Events</a>
						</li>
						<li class="<?php echo $class == 'news' ? 'active' : ''; ?>">
							<a href="/ministry/<?php echo $ministry['_id']->{'$id'}; ?>/news#main">News</a>
						</li>
						<li class="<?php echo $class == 'gallery' ? 'active' : ''; ?>">
							<a href="/ministry/<?php echo $ministry['_id']->{'$id'}; ?>/gallery#main">Gallery</a>
						</li>
					</ul>
				</div>

				<div class="panel-main">
					<div class="events-container">
						<?php if (!empty($events)): ?>
							<?php foreach ($events as $event): ?>
								<div class="event-template clearfix">
									<div class="event-image">
										<a href="#">
											<img src="/uploads/event/<?php echo $event['event_image']['file_name']; ?>" alt="event image">
										</a>
									</div>
									<div class="event-description">
										<h5><?php echo ucwords($event['event_title']); ?></h5>
										<p class="date"><?php echo date('F j, Y', $event['event_start']).' - '.date('F j, Y', $event['event_end']); ?></p>
										<p class="text">
											<?php echo $event['event_text'] ?>
										</p>
										<div class="actions">
											<a href="#" class="read-more"><i class="fa fa-search-plus"></i>&nbsp; Read More</a> |
											<a href="#" class="join"><i class="fa fa-plus"></i>&nbsp; Join Now</a>
										</div>
									</div>
								</div>
							<?php endforeach ?>
						<?php else: ?>
							<p>No events yet!</p>
						<?php endif ?>
					</div>
				</div>
			</section>

			<!-- left panel profile template -->
			<section class="right-panel panel">
				<div class="panel-header clearfix">
					<p>News</p>
					<a href="#" class="view-more">View More</a>
				</div>
				<div class="news-list">					
					<div class="news-template clearfix">
						<div class="news-day-month">
							<div class="news-month">OCT</div>
							<div class="news-day">02</div>
						</div>
						<div class="news-info">
							<a href="#">Oranizing a Charity Parachute Jump</a>
						</div>
					</div>
					<div class="news-template clearfix">
						<div class="news-day-month">
							<div class="news-month">OCT</div>
							<div class="news-day">02</div>
						</div>
						<div class="news-info">
							<a href="#">Oranizing a Charity Parachute Jump</a>
						</div>
					</div>
					<div class="news-template clearfix">
						<div class="news-day-month">
							<div class="news-month">OCT</div>
							<div class="news-day">02</div>
						</div>
						<div class="news-info">
							<a href="#">Oranizing a Charity Parachute Jump</a>
						</div>
					</div>
				</div>
			</section>
		</div>
	</section>
</div>