<div class="edit-event-container container">
	<section class="page-header event-header row">
		<div class="col-md-12 clearfix">
			<h2 class="pull-left">Edit Ministry <small>Settings</small></h2>
			<a href="/events" class="btn btn-success pull-right"><i class="fa fa-th-list"></i>&nbsp; Back to Events List</a>
		</div>
	</section>
	<section class="edit-event-main clearfix">
		<?php foreach ($errors as $error): ?>
			<div class="alert alert-danger"><?php echo $error; ?></div>
		<?php endforeach ?>

		<?php foreach ($msg as $m): ?>
			<div class="alert alert-<?php echo $m['type']; ?>"><?php echo $m['msg']; ?></div>
		<?php endforeach ?>

		<div class="panel panel-default">
			<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Event Information</div>
			<div class="panel-body">
				<?php if (!empty($post['event_images'])): ?>
					<div class="row">
						<div class="col-md-12 clearfix">
					        <label for="event_images">Event Images</label>
							<div class="event-uploaded-images row">
								<div class="col-md-12 clearfix">
									<?php foreach ($post['event_images'] as $key => $image): ?>
										<div class="upload-image">
											<div class="image-thumbnail">
												<img src="/uploads/event/<?php echo $image['file_name']; ?>">
											</div>
											<a href="/event/edit/<?php echo $post['event_id']; ?>?action=remove_image&id=<?php echo $image['file_id']; ?>" 
											class="upload-actions remove-event-image" data-ids="<?php echo $image['file_id']; ?>">
												<i class="fa fa-times-circle fa-5x"></i>
											</a>
											<?php if ($image['file_primary'] == 1): ?>
												<span class="primary-label upload-primary">
													Primary Event Image
													<i class="fa fa-star"></i>
												</span>
											<?php else: ?>
												<a href="/event/edit/<?php echo $post['event_id']; ?>?action=set_primary&id=<?php echo $image['file_id']; ?>"
												class="primary-label upload-not-primary set-primary" data-id="<?php echo $image['file_id']; ?>">Set as Primary</a>
											<?php endif ?>
										</div>
									<?php endforeach; ?>
								</div>
							</div>
						</div>
					</div>
				<?php endif ?>

				<form action="" method="post" enctype="multipart/form-data" id="event_images_form" class="event-images-form">
					<div class="upload-input-container">
						<div class="form-input">
						    <input name="file[]" type="file" />
						</div>
					</div>

				    <button class="add-more btn btn-info btn-sm"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Add More Files</button>
				    <input type="submit" class="btn btn-primary btn-sm" value="Upload File" id="upload"/>
			    </form>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Event Information</div>
			<div class="panel-body">
				<form action="" method="post">
					<div class="form-group">
						<label for="event_title">Event Title</label>
						<input type="text" name="event_title" id="event_title" class="form-control" placeholder="Title"
						value="<?php echo isset($post['event_title']) ? $post['event_title'] : ''; ?>">
					</div>
					<div class="form-group">
						<label for="event_text">Event Text</label>
						<textarea name="event_text" id="event_text" class="form-control" cols="30" rows="10" placeholder="Description"><?php echo isset($post['event_text']) ? $post['event_text'] : ''; ?></textarea>
					</div>

					<div class="form-group event-date">
						<div class="row">
							<div class="col-md-3">
								<label>Start Date</label>
								<span class="input-group">
									<input class="form-control" name="event_start" id="start-date-display" type="text" 
									value="<?php echo isset($_POST['event_start']) ? $post['event_start'] : date('Y-m-d', $post['event_start']); ?>" readonly>

									<span class="input-group-btn">
										<a href="#" id="date-start" class="btn btn-default" data-date-format="yyyy-mm-dd">
											<i class="glyphicon glyphicon-th"></i>
										</a>
									</span>
								</span>
							</div>
							<div class="col-md-3">
								<label>End Date</label>
								<div class="input-group">
									<input class="form-control" name="event_end" id="end-date-display" type="text" 
									value="<?php echo isset($_POST['event_end']) ? $post['event_end'] : date('Y-m-d', $post['event_end']); ?>" readonly>

									<span class="input-group-btn">
										<a href="#" id="date-end" class="btn btn-default" data-date-format="yyyy-mm-dd">
											<i class="glyphicon glyphicon-th"></i>
										</a>
									</span>
								</div>
							</div>
							<div class="col-md-6">
								<div class="alert alert-danger hide"></div>
							</div>
						</div>
					</div>

					<div class="form-group">
						<label for="event_active">Event Active</label>
						<div class="radio">
							<label>
								<input type="radio" name="event_active" value="1"
								<?php echo isset($post['event_active']) && $post['event_active'] == 1 ? 'checked="checked"' : ''; ?>
								<?php echo !isset($post['event_active']) ? 'checked="checked"' : ''; ?>> Active
							</label>
						</div>
						<div class="radio">
							<label>
								<input type="radio" name="event_active" value="0"
								<?php echo isset($post['event_active']) && $post['event_active'] == 0 ? 'checked="checked"' : ''; ?>> Inactive
							</label>
						</div>
					</div>
					<div class="form-group">
						<input type="submit" class="btn btn-primary" name="edit_event" value="Submit">
					</div>
				</form>
			</div>
		</div>
	</section>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('button.add-more').click(function(e){
	        e.preventDefault();
	        var append_input = '<div class="form-input"> \
	            <input name="file[]"" type="file"/> &nbsp; \
	            <a href="#" class="remove-input-upload btn btn-xs btn-danger"><i class="glyphicon glyphicon-remove-sign"></i>&nbsp; Remove</a> \
	        </div>';
	        
	        $(this).parent().find('div.upload-input-container').append(append_input);
	    });

		$(document).on('click', 'a.remove-input-upload', function(e){
	    	e.preventDefault();
	    	$(this).parent().remove();
	    });

	    $('div.upload-image').mouseenter(function(){
	    	var $this = $(this);

	    	$this.find('a.remove-event-image').fadeIn('fast');
	    	$this.find('.primary-label').fadeIn('fast');
	    	$this.css({ opacity: 0.70 });
	    });

	    $('div.upload-image').mouseleave(function(){
	    	var $this = $(this);

	    	$this.find('a.remove-event-image').fadeOut('fast');
	    	$this.find('.primary-label').fadeOut('fast');
	    	$this.css({ opacity: 1 });
	    });

	    $('a.remove-event-image').click(function(){
	    	if (confirm('Are you sure?')) { return true; };
	    	return false;
	    });
	});
</script>